#' Add Values to Key
#'
#' Adds values to an encoding key as generated by `make_encoding_key()`.
#'
#' @param values_to_add A vector of values to add to key.
#' @param prime_key The old keys to which values are to be added.
#'
#' @usage add_values_to_key(values_to_add, prime_key)
#'
#' @return A vector containing a new key, including both old and new values.
#' @export
#' @seealso [primr::make_encoding_key()]
#' @md
#'
#' @examples
#' # Add "Arthropod" to encoding key.
#' new_prime_key <- add_values_to_key("Arthropod", c(Fish = 2, Mammal = 3, Bird = 5))
add_values_to_key <- function(values_to_add, prime_key) {
  return(new_prime_key)
}
