#' Append Values
#'
#' Appends values to a value that has been previously encoded by
#' `encode_value()`, using a key generated by `make_encoding_key()`.
#'
#' @param encoded_value The old encoded value, as generated by `encode_value()`.
#' @param values_to_append A vector of values to add to the encoded value.
#' @param prime_key An encoding key, as generated by `make_encoding_key()`.
#'
#' @usage append_values(encoded_value, values_to_append, prime_key)
#'
#' @return A double containing an integer with the new encoded value.
#' @export
#' @seealso [primr::encode_value()]
#' @seealso [primr::make_encoding_key()]
#' @md
#'
#' @examples
#' # Add "Arthropod" to the previously encoded value.
#' new_encoded_value <- append_values(6, "Arthropod", c(Fish = 2, Mammal = 3, Bird = 5, Arthropod = 7))
append_values <- function(encoded_value, values_to_append, prime_key) {
  return(new_encoded_value)
}
