#' Check If Factorization is Possible
#'
#' A helper function meant that throws an error if a value cannot be factorized
#' using the supplied prime numbers.
#'
#' @param values_to_factorize The numeric on which to attempt factorization.
#' @param prime_key An encoding key as generated by `make_encoding_key()`.
#' @param error_message The error message to print if factorization is not
#'   possible.
#'
#' @usage check_if_factorization_is_possible(values_to_factorize, prime_key,
#'   error_message)
#'
#' @return Does not return a value.
#' @export
#' @seealso [primr::make_encoding_key()]
#' @md
#'
#' @import assertthat
#'
#' @examples
#' # No examples supplied as this function is meant as a helper function and the fact that i throws an error.
check_if_factorization_is_possible <- function(values_to_factorize, prime_key, error_message) {
  check_values <- values_to_factorize
  for (i in prime_key[values_to_factorize %% prime_key == 0]) {
    check_values <- check_values / i
  }
  assertthat::assert_that(check_values == 1, msg = error_message)
}
