#' Decode Value
#'
#' Takes a product from `encode_value()` and returns a vector of decoded values using a key as generated by `make_encoding_key()`.
#'
#' @param value_to_decode A product of prime numbers multiplied using `encode_value()`.
#' @param prime_key A key as generated by `make_encoding_key()`
#'
#' @usage decode_value(value_to_decode, prime_key)
#'
#' @return A vector of decoded values.
#' @export
#' @seealso [primr::encode_value()]
#' @seealso [primr::make_encoding_key()]
#' @md
#'
#' @examples
#' # Return a vector containing "Mammal" and "Bird".
#' decoded_values <- encode_value(15, c(Fish = 2, Mammal = 3, Bird = 5))
decode_value <- function(value_to_decode, prime_key) {
  return(decoded_values)
}
