#' Encode Value
#'
#' Takes a vector and returns an integer that is a product of the prime keys
#' corresponding to the values in the vector. The second argument takes an
#' encoding key as generated by `make_encoding_key()`. Values can be decoded
#' using `decode_value()`.
#'
#' @param value_to_encode A vector of values to encode.
#' @param prime_key An encoding key, as generated by `make_encoding_key()`.
#'
#' @usage encode_value(value_to_encode, prime_key)
#'
#' @return A double, containing an integer value.
#' @export
#' @seealso [primr::make_encoding_key()]
#' @seealso [primr::decode_value()]
#' @md
#'
#' @examples
#' # Generate a product equal to 15.
#' encoded_value <- encode_value(c('Mammal', 'Bird'), c(Fish = 2, Mammal = 3, Bird = 5))
encode_value <- function(values_to_encode, prime_key) {
  return(encoded_value)
}
