# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate Primes
#'
#' Generates a list of prime numbers, starting at 2. The prime numbers are used
#' by `make_encoding_key()` to generate prime number keys for encoding.
#'
#' @param number_of_primes A positive integer. The number of prime numbers
#'   desired. Non-integers will be rounded to the nearest smaller prime.
#'
#' @usage generate_primes(number_of_primes)
#'
#' @return A double vector of prime numbers starting at 2.
#' @export
#' @md
#'
#' @seealso [primr::make_encoding_key()]
#'
#' @examples
#' # Return a vector containing 2, 3, and 5.
#' vector_of_primes <- generate_primes(3)
generate_primes <- function(number_of_primes) {
    .Call(`_primr_generate_primes`, number_of_primes)
}

