#' Remove Values
#'
#' Removes values from an encoded value.
#'
#' @param encoded_value An encoded value, as encoded by `encode_value()`.
#' @param values_to_remove A vector containing values to remove from encoded value.
#' @param prime_key An encoding key, as generated by `make_encoding_key()`.
#'
#' @usage remove_values(encoded_value, values_to_remove, prime_key)
#'
#' @return A double, containing an integer, where the values to remove has been removed.
#' @export
#' @seealso [primr::encode_value()]
#' @seealso [primr::make_encoding_key()]
#' @md
#'
#' @examples
#' # Remove "Fish" from encoded value.
#' new_encoded_value <- remove_values(6, "Fish", c(Fish = 2, Mammal = 3, Bird = 5, Arthropod = 7))
remove_values <- function(encoded_value, values_to_remove, prime_key) {
  return(new_encoded_value)
}
